### ISSUE TITLE
ERR unknown command `config`, with args beginning with: `get`, `*`

### ISSUE THREAD

**Issue by wbotelhos** [BaseSecrete/redis_dashboard#11]
Accessing menu `config` or `sloglog`:

Redis: `4.1.3`

```
Redis::CommandError - ERR unknown command `config`, with args beginning with: `get`, `*`,:
	/usr/local/ruby/gem/gems/redis-4.1.3/lib/redis/client.rb:126:in `call'
	/usr/local/ruby/gem/gems/redis-4.1.3/lib/redis.rb:206:in `block in config'
	/usr/local/ruby/gem/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
	/usr/local/ruby/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	/usr/local/ruby/gem/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
	/usr/local/ruby/gem/gems/redis-4.1.3/lib/redis.rb:205:in `config'
	/usr/local/ruby/gem/bundler/gems/redis_dashboard-956450c2181d/lib/redis_dashboard/client.rb:14:in `config'
	/usr/local/ruby/gem/bundler/gems/redis_dashboard-956450c2181d/lib/redis_dashboard/client.rb:33:in `slow_commands'
	/usr/local/ruby/gem/bundler/gems/redis_dashboard-956450c2181d/lib/redis_dashboard/application.rb:32:in `block in <class:Application>'
```

**Comment by alexisbernard** [comment]
I can't reproduce with redis gem 4.1.3. What is your Redis server version ? I already tried with 4.0.9, 5.0.8 and 6.0rc3.

**Comment by wbotelhos** [comment]
@alexisbernard I'm using ElastiCache on version `5.0.6`
